skip_registry_checks_reason: "Not published to a registry yet; will add a PyPI badge after first release."
skip_checklist_checks_reason: "OpenSSF Best Practices badge not set up yet."
ignore_commented_badges: true
