name: "Setup just"
description: "Install just command runner for use in workflows"
runs:
  using: composite
  steps:
    - name: Install just
      shell: bash
      run: |
        # Determine platform
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        # Detect Windows (Git Bash reports mingw64_nt-*)
        case "$OS" in
          mingw*|msys*|cygwin*) OS="windows" ;;
        esac

        # Map architecture names
        case "$ARCH" in
          x86_64) ARCH="x86_64" ;;
          aarch64|arm64) ARCH="aarch64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        # Set version
        VERSION="1.38.0"

        # Download from GitHub releases
        if [ "$OS" = "darwin" ]; then
          TARGET="just-$VERSION-$ARCH-apple-darwin"
          EXT="tar.gz"
        elif [ "$OS" = "linux" ]; then
          TARGET="just-$VERSION-$ARCH-unknown-linux-musl"
          EXT="tar.gz"
        elif [ "$OS" = "windows" ]; then
          TARGET="just-$VERSION-$ARCH-pc-windows-msvc"
          EXT="zip"
        else
          echo "Unsupported OS: $OS"
          exit 1
        fi

        echo "Downloading just $VERSION for $OS ($ARCH)..."
        curl -fsSL "https://github.com/casey/just/releases/download/$VERSION/$TARGET.$EXT" -o "just.$EXT"

        # Extract and install
        if [ "$EXT" = "zip" ]; then
          unzip -o -q "just.$EXT"
          mkdir -p "$HOME/.local/bin"
          mv just.exe "$HOME/.local/bin/"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          rm "just.$EXT" LICENSE
          # Verify (use full path since GITHUB_PATH takes effect in next step)
          "$HOME/.local/bin/just.exe" --version
        else
          tar -xzf "just.$EXT"
          sudo mv just /usr/local/bin/just
          sudo chmod +x /usr/local/bin/just
          rm "just.$EXT"
          # Verify
          just --version
        fi

        echo "✅ just $VERSION installed successfully"
